services:
  office-demo:
    build:
      context: .
      dockerfile: Dockerfile.demo
    container_name: donggricompany
    ports:
      - "7777:7777"
      - "4315:4315"
    volumes:
      - ./.local:/app/.local
