export const STEP3_ALLOWED_ROUTES = {
  BOOTSTRAP_STATE: "/api/bootstrap/state",
  BOOTSTRAP_INIT: "/api/bootstrap/init",
  PROVIDERS: "/api/providers",
  PROVIDERS_PROBE: "/api/providers/probe",
  ROLEPACKS: "/api/rolepacks",
  ACCOUNT_POOLS: "/api/account-pools",
  ACCOUNT_POOL_BY_ID: "/api/account-pools/:id",
  ACCOUNT_POOL_FATIGUE: "/api/account-pools/:id/fatigue",
  RUNTIME_PROFILES: "/api/runtime-profiles",
  RUNTIME_PROFILE_BY_ID: "/api/runtime-profiles/:id",
  RUNTIME_ROUTER_SIMULATE: "/api/runtime-router/simulate",
  RUNTIME_ROUTER_RESOLVE: "/api/runtime-router/resolve",
  PROVIDER_PROBES_RUN: "/api/provider-probes/run",
  PROVIDER_PROBES_HISTORY: "/api/provider-probes/history",
  AGENT_MODELS: "/api/agent-models",
  AGENT_MODEL_BY_ID: "/api/agent-models/:agentId",
  OAUTH_PROVIDER_START: "/api/oauth/:provider/start",
  OAUTH_PROVIDER_CALLBACK: "/api/oauth/:provider/callback",
  OAUTH_PROVIDER_STATUS: "/api/oauth/:provider/status",
  OAUTH_PROVIDER_DISCONNECT: "/api/oauth/:provider/disconnect",
  OFFICE_BOOTSTRAP: "/api/office/bootstrap",
  WORKSPACES: "/api/workspaces",
  EMPLOYEES: "/api/employees",
  SESSIONS_ACTIVE: "/api/sessions/active",
  SESSIONS_BY_ID: "/api/sessions/:id",
  TIMELINE: "/api/timeline",
  EVENTS_STREAM: "/api/events/stream",
  OFFICE_RUNTIME_STATE: "/api/office/runtime/state",
  OFFICE_RUNTIME_COMMAND: "/api/office/runtime/command",
  OFFICE_LOGS: "/api/office/logs",
  OFFICE_THREADS: "/api/office/threads",
  OFFICE_THREAD_MESSAGES: "/api/office/threads/:id/messages",
  OFFICE_THREAD_STATUS: "/api/office/threads/:id/status",
  OFFICE_KANBAN_TASKS: "/api/office/kanban/tasks",
  OFFICE_KANBAN_TASK_BY_ID: "/api/office/kanban/tasks/:id",
  OFFICE_MEETINGS: "/api/office/meetings",
  OFFICE_MEETING_START: "/api/office/meetings/:id/start",
  OFFICE_MEETING_COMPLETE: "/api/office/meetings/:id/complete",
  OFFICE_MEETING_BY_ID: "/api/office/meetings/:id",
  OFFICE_CLI_RUN: "/api/office/cli/run",
  OFFICE_CLI_STOP: "/api/office/cli/stop/:taskId",
  OFFICE_CLI_LOGS: "/api/office/cli/logs/:taskId",
  OFFICE_CLI_SUBTASKS: "/api/office/cli/subtasks/:taskId",
  OFFICE_CLI_ACTIVE: "/api/office/cli/active",
  OFFICE_RUNNERS: "/api/office/runners",
  OFFICE_RUNNERS_QUEUE: "/api/office/runners/queue",
  OFFICE_RUNNERS_ACTIVATE: "/api/office/runners/activate",
  OFFICE_RUNNERS_DEACTIVATE: "/api/office/runners/deactivate",
  SESSION_OVERRIDE_RUNTIME: "/api/sessions/:id/override-runtime",
  SESSION_PAUSE: "/api/sessions/:id/pause",
  SESSION_RESUME: "/api/sessions/:id/resume"
} as const;

export const STEP3_EXCLUDED_ROUTE_PREFIXES = [
  "/api/oauth",
  "/api/auth",
  "/api/providers/:provider/login",
  "/api/providers/:provider/callback",
  "/api/providers/:provider/token",
  "/api/providers/:provider/refresh",
  "/api/providers/:provider/raw-command",
  "/api/telegram",
  "/api/webhooks"
] as const;

export const buildStep3Route = {
  accountPoolById: (id: string): string => `/api/account-pools/${id}`,
  accountPoolFatigue: (id: string): string => `/api/account-pools/${id}/fatigue`,
  runtimeProfileById: (id: string): string => `/api/runtime-profiles/${id}`,
  agentModelById: (agentId: string): string => `/api/agent-models/${agentId}`,
  oauthProviderStart: (provider: string): string => `/api/oauth/${provider}/start`,
  oauthProviderCallback: (provider: string): string => `/api/oauth/${provider}/callback`,
  oauthProviderStatus: (provider: string): string => `/api/oauth/${provider}/status`,
  oauthProviderDisconnect: (provider: string): string => `/api/oauth/${provider}/disconnect`,
  officeThreadMessages: (id: string): string => `/api/office/threads/${id}/messages`,
  officeThreadStatus: (id: string): string => `/api/office/threads/${id}/status`,
  officeKanbanTaskById: (id: string): string => `/api/office/kanban/tasks/${id}`,
  officeMeetingById: (id: string): string => `/api/office/meetings/${id}`,
  officeMeetingStart: (id: string): string => `/api/office/meetings/${id}/start`,
  officeMeetingComplete: (id: string): string => `/api/office/meetings/${id}/complete`,
  officeCliStop: (taskId: string): string => `/api/office/cli/stop/${taskId}`,
  officeCliLogs: (taskId: string): string => `/api/office/cli/logs/${taskId}`,
  officeCliSubtasks: (taskId: string): string => `/api/office/cli/subtasks/${taskId}`,
  sessionsById: (id: string): string => `/api/sessions/${id}`,
  sessionOverrideRuntime: (id: string): string => `/api/sessions/${id}/override-runtime`,
  sessionPause: (id: string): string => `/api/sessions/${id}/pause`,
  sessionResume: (id: string): string => `/api/sessions/${id}/resume`
} as const;
