import type { ContinuityCheckpoint } from "./checkpoint-contract.js";

export function continuityCheckpointFixture(overrides: Partial<ContinuityCheckpoint> = {}): ContinuityCheckpoint {
  return {
    schema_version: 1,
    checkpoint_id: "checkpoint:fixture:1",
    previous_checkpoint_id: null,
    sequence: 1,
    project_id: "project:DonggriCompany",
    task_id: "task:continuity:fixture",
    source_run_id: "run:codex:fixture",
    source_provider: "codex",
    source_account_pool_id: "codex-fixture",
    source_account_label: "Codex fixture",
    target_provider: "claude",
    target_account_pool_id: "claude-fixture",
    target_account_label: "Claude fixture",
    target_run_id: null,
    provider_native_session_id: null,
    dispatch_id: null,
    status: "ready_for_transfer",
    objective: "Continue one task across providers",
    acceptance_criteria: ["identity preserved"],
    completed: ["source paused"],
    pending: ["target validation"],
    blockers: [],
    next_safe_action: "Validate target",
    workspace: {
      canonical_project_path: "C:\\fixture",
      git_root: "C:\\fixture",
      branch: "main",
      head: "a".repeat(40),
      dirty: false,
      changed_paths: [],
      workspace_digest: "b".repeat(64),
      captured_at: "2026-08-28T09:00:00+09:00",
    },
    verification: [{ command: "pnpm test", status: "passed", summary: "fixture passed" }],
    evidence_refs: ["evidence.md#fixture"],
    approval_ref: "APR-FIXTURE",
    idempotency_key: "continuity:fixture:1",
    created_by: "IMPLEMENT",
    created_at: "2026-08-28T09:01:00+09:00",
    ...overrides,
  };
}
