import type { UiLanguage } from "../../i18n";

type Locale = UiLanguage;
export type SkillLibraryT = (messages: Record<Locale, string>) => string;

function label(ko: string): Record<Locale, string> {
  return { ko, en: ko, ja: ko, zh: ko };
}

export const SKILL_LIBRARY_TEXT = {
  "loading.catalog": label("Skill 문서고를 불러오는 중입니다."),
  "loading.failed": label("Skill 데이터를 불러오지 못했습니다."),
  "action.retry": label("다시 시도"),
  "action.refresh": label("새로고침"),
  "action.refreshing": label("새로고침 중"),
  "action.close": label("닫기"),
  "action.cancel": label("취소"),
  "action.delete": label("삭제"),
  "footer.sources": label("출처: Donggri 기본 Skill, skills.sh 전체 카탈로그, 사용자 Skill"),
  "header.title": label("Agent Skills 문서고"),
  "header.subtitle": label("검증된 기법을 직원과 CLI 담당자가 바로 재사용할 수 있게 정리합니다."),
  "header.addCustomTitle": label("사용자 Skill을 직접 등록합니다."),
  "header.addCustom": label("사용자 Skill 추가"),
  "header.refreshTitle": label("skills.sh 카탈로그와 Codex 설치 상태를 다시 확인합니다."),
  "header.registeredSkills": label("등록된 Skill"),
  "header.countSummary": label("전체 {total}개 (카탈로그 {catalog}개 + 사용자 {custom}개)"),
  "header.searchPlaceholder": label("Skill 검색 (이름, 저장소, 카테고리)"),
  "sort.rank": label("추천순"),
  "sort.installs": label("설치순"),
  "sort.name": label("이름순"),
  "category.all": label("전체"),
  "category.codex-specialist": label("Codex 전문 기능"),
  "category.provider-oauth": label("OAuth / 실행 계정"),
  "category.google-gemini": label("Google / Gemini"),
  "category.google-stitch": label("Google / Stitch"),
  "category.donggri-operations": label("Donggri 운영"),
  "category.external-catalog": label("외부 Skill 카탈로그"),
  "category.custom": label("사용자 Skill"),
  "category.summaryAll": label("전체 {all}개를 집계했습니다. 카탈로그 {catalog}개, 사용자 Skill {custom}개입니다."),
  "category.summarySearchAll": label("검색 결과 {filtered}개를 표시합니다. 전체 집계는 {all}개입니다."),
  "category.summaryFiltered": label("{filtered}개 Skill을 표시합니다{suffix}."),
  "category.searchSuffix": label(' · "{search}" 검색 결과'),
  "oauth.storageUnavailable": label("저장소 확인 필요"),
  "oauth.executionReady": label("실행 준비 완료"),
  "oauth.reauthRequired": label("재연결 필요"),
  "oauth.connectable": label("연결 가능"),
  "oauth.unavailable": label("연결 불가"),
  "grid.installFailed": label("Codex 앱 설치 실패: {error}"),
  "grid.codexInstalled": label("Codex 설치됨"),
  "grid.installs": label("설치"),
  "grid.installToCodexTitle": label("이 repo 기본 Skill을 Codex 앱 Skill 홈에 설치합니다."),
  "grid.installing": label("설치 중"),
  "grid.installed": label("설치됨"),
  "grid.installToCodex": label("Codex 앱에 설치"),
  "grid.learnTitle": label("선택한 CLI 담당자에게 이 Skill을 학습시킵니다."),
  "grid.learn": label("학습"),
  "grid.copied": label("복사됨"),
  "grid.copy": label("복사"),
  "grid.detailsLoading": label("상세 정보를 불러오는 중입니다."),
  "grid.detailsError": label("상세 정보를 불러오지 못했습니다."),
  "grid.whenToUse": label("사용 시점"),
  "grid.weekly": label("주간 설치"),
  "grid.firstSeen": label("최초 등록"),
  "grid.targetPlatforms": label("지원 환경"),
  "grid.noResults": label("검색 결과가 없습니다."),
  "grid.tryDifferentKeyword": label("다른 키워드나 카테고리로 다시 검색하세요."),
  "custom.title": label("사용자 Skill 추가"),
  "custom.description": label("skills.md 파일을 첨부하고 학습 대상 CLI 담당자를 선택하세요."),
  "custom.nameLabel": label("Skill 이름"),
  "custom.namePlaceholder": label("예: project-review-skill"),
  "custom.nameHelp": label("영문, 숫자, 하이픈, 언더스코어만 사용할 수 있습니다."),
  "custom.fileLabel": label("skills.md 파일"),
  "custom.chooseFile": label("파일 선택"),
  "custom.providersLabel": label("학습 대상 CLI 담당자"),
  "custom.none": label("배정 없음"),
  "custom.submitting": label("등록 중"),
  "custom.startTraining": label("학습 시작"),
  "custom.sectionTitle": label("사용자 Skill"),
  "custom.noMatches": label("검색 조건에 맞는 사용자 Skill이 없습니다."),
  "custom.fileReadFailed": label("파일을 읽지 못했습니다."),
  "custom.invalidName": label("Skill 이름은 영문, 숫자, 하이픈, 언더스코어만 사용할 수 있으며 최대 80자입니다."),
  "learning.title": label("스킬 학습 스쿼드"),
  "learning.running": label("학습 중"),
  "learning.installCommand": label("설치 명령"),
  "learning.selectProviders": label("학습시킬 CLI 담당자를 선택하세요. 여러 담당자를 동시에 선택할 수 있습니다."),
  "learning.selectedCount": label("명 선택됨"),
  "learning.noAssignedMember": label("배정된 직원 없음"),
  "learning.bonk": label("해제"),
  "learning.unavailable": label("사용 불가"),
  "learning.learned": label("학습됨"),
  "learning.selected": label("선택됨"),
  "learning.idle": label("대기"),
  "learning.unlearning": label("학습 해제 중"),
  "learning.unlearn": label("학습 해제"),
  "learning.jobStatus": label("작업 상태"),
  "learning.noLogs": label("아직 로그가 없습니다."),
  "learning.learning": label("학습 중"),
  "learning.startLearning": label("학습 시작"),
  "classroom.training": label('"{skill}" Skill 교육을 진행 중입니다.'),
  "classroom.studying": label("CLI 담당자들이 Skill 문서를 학습하고 있습니다."),
  "memory.title": label("Skill 학습 메모리"),
  "memory.subtitle": label("CLI별 학습 이력"),
  "audit.pass": label("통과"),
  "audit.warn": label("경고"),
  "audit.pending": label("대기"),
  "audit.fail": label("실패"),
  "role.team_leader": label("팀장"),
  "role.senior": label("시니어"),
  "role.junior": label("주니어"),
  "role.intern": label("인턴"),
  "learnStatus.queued": label("대기 중"),
  "learnStatus.running": label("진행 중"),
  "learnStatus.succeeded": label("완료"),
  "learnStatus.failed": label("실패"),
} as const satisfies Record<string, Record<Locale, string>>;

export type SkillLibraryTextKey = keyof typeof SKILL_LIBRARY_TEXT;

export function skillText(t: SkillLibraryT, key: SkillLibraryTextKey): string {
  return t(SKILL_LIBRARY_TEXT[key]);
}

export function skillTextVars(
  t: SkillLibraryT,
  key: SkillLibraryTextKey,
  vars: Record<string, string | number>,
): string {
  return skillText(t, key).replace(/\{(\w+)\}/g, (match, name: string) => {
    const value = vars[name];
    return value === undefined ? match : String(value);
  });
}
