import type { UiLanguage } from "../../i18n";

type Locale = UiLanguage;
export type SkillLibraryT = (messages: Record<Locale, string>) => string;

export const SKILL_LIBRARY_TEXT = {
  "loading.catalog": {
    ko: "Skill 카탈로그를 불러오는 중...",
    en: "Loading skill catalog...",
    ja: "Loading skill catalog...",
    zh: "Loading skill catalog...",
  },
  "loading.failed": {
    ko: "Skill 데이터를 불러오지 못했습니다",
    en: "Unable to load skills data",
    ja: "Unable to load skills data",
    zh: "Unable to load skills data",
  },
  "action.retry": { ko: "다시 시도", en: "Retry", ja: "Retry", zh: "Retry" },
  "action.refresh": { ko: "새로고침", en: "Refresh", ja: "Refresh", zh: "Refresh" },
  "action.refreshing": { ko: "새로고침 중...", en: "Refreshing...", ja: "Refreshing...", zh: "Refreshing..." },
  "footer.sources": {
    ko: "출처: Donggri seed skills + skills.sh 전체 카탈로그 + 사용자 Skill",
    en: "Sources: Donggri seed skills + full skills.sh catalog + custom skills",
    ja: "Sources: Donggri seed skills + full skills.sh catalog + custom skills",
    zh: "Sources: Donggri seed skills + full skills.sh catalog + custom skills",
  },
  "header.title": {
    ko: "Agent Skills 문서고",
    en: "Agent Skills Library",
    ja: "Agent Skills ライブラリ",
    zh: "Agent Skills 资料库",
  },
  "header.subtitle": {
    ko: "Donggri seed skills · skills.sh 전체 카탈로그 · 사용자 Skill",
    en: "Donggri seed skills · full skills.sh catalog · custom skills",
    ja: "Donggri seed skills · skills.sh 全体カタログ · カスタム Skill",
    zh: "Donggri seed skills · skills.sh 全量目录 · 自定义 Skill",
  },
  "header.addCustomTitle": {
    ko: "커스텀 스킬 직접 추가",
    en: "Add custom skill",
    ja: "カスタムスキルを追加",
    zh: "添加自定义技能",
  },
  "header.addCustom": {
    ko: "커스텀 스킬 추가",
    en: "Add Custom Skill",
    ja: "カスタムスキル追加",
    zh: "添加自定义技能",
  },
  "header.refreshTitle": {
    ko: "skills.sh 카탈로그와 Codex 설치 상태를 다시 확인",
    en: "Refresh skills.sh catalog and Codex install state",
    ja: "Refresh skills.sh catalog and Codex install state",
    zh: "Refresh skills.sh catalog and Codex install state",
  },
  "header.registeredSkills": {
    ko: "등록된 스킬",
    en: "Registered skills",
    ja: "登録済みスキル",
    zh: "已收录技能",
  },
  "header.countSummary": {
    ko: "총 {total} (catalog {catalog} + custom {custom})",
    en: "Total {total} (catalog {catalog} + custom {custom})",
    ja: "合計 {total} (catalog {catalog} + custom {custom})",
    zh: "总计 {total} (catalog {catalog} + custom {custom})",
  },
  "header.searchPlaceholder": {
    ko: "스킬 검색... (이름, 저장소, 카테고리)",
    en: "Search skills... (name, repo, category)",
    ja: "スキル検索... (名前、リポジトリ、カテゴリ)",
    zh: "搜索技能...（名称、仓库、分类）",
  },
  "sort.rank": { ko: "순위순", en: "By Rank", ja: "順位順", zh: "按排名" },
  "sort.installs": { ko: "설치순", en: "By Installs", ja: "インストール順", zh: "按安装量" },
  "sort.name": { ko: "이름순", en: "By Name", ja: "名前順", zh: "按名称" },
  "category.all": { ko: "전체", en: "All", ja: "すべて", zh: "全部" },
  "category.codex-specialist": {
    ko: "Codex 전문 기능",
    en: "Codex Specialist",
    ja: "Codex 専門機能",
    zh: "Codex 专业功能",
  },
  "category.provider-oauth": {
    ko: "OAuth / 실행 계정",
    en: "OAuth / Execution Accounts",
    ja: "OAuth / 実行アカウント",
    zh: "OAuth / 执行账号",
  },
  "category.google-gemini": {
    ko: "Google / Gemini",
    en: "Google / Gemini",
    ja: "Google / Gemini",
    zh: "Google / Gemini",
  },
  "category.google-stitch": {
    ko: "Google / Stitch",
    en: "Google / Stitch",
    ja: "Google / Stitch",
    zh: "Google / Stitch",
  },
  "category.donggri-operations": {
    ko: "Donggri 운영",
    en: "Donggri Operations",
    ja: "Donggri 運用",
    zh: "Donggri 运营",
  },
  "category.external-catalog": {
    ko: "외부 Skill 카탈로그",
    en: "External Skill Catalog",
    ja: "外部 Skill カタログ",
    zh: "外部 Skill 目录",
  },
  "category.custom": { ko: "사용자 Skill", en: "Custom Skills", ja: "カスタム Skill", zh: "自定义 Skill" },
  "category.summaryAll": {
    ko: "총 {all}개 집계중 (카탈로그 {catalog} + 커스텀 {custom})",
    en: "Total {all} aggregated (catalog {catalog} + custom {custom})",
    ja: "合計 {all} 件を集計中 (catalog {catalog} + custom {custom})",
    zh: "当前汇总 {all} 个（catalog {catalog} + custom {custom}）",
  },
  "category.summarySearchAll": {
    ko: "카탈로그 검색 결과 {filtered}개 · 전체 집계 {all}개",
    en: "Catalog search results {filtered} · total aggregated {all}",
    ja: "カタログ検索結果 {filtered} 件 · 全体集計 {all} 件",
    zh: "目录搜索结果 {filtered} 个 · 总汇总 {all} 个",
  },
  "category.summaryFiltered": {
    ko: "{filtered}개 스킬 표시중{suffix}",
    en: "{filtered} skills shown{suffix}",
    ja: "{filtered}件のスキルを表示中{suffix}",
    zh: "已显示 {filtered} 个技能{suffix}",
  },
  "category.searchSuffix": {
    ko: ' · "{search}" 검색 결과',
    en: ' · "{search}" search results',
    ja: " · 「{search}」検索結果",
    zh: " · “{search}” 搜索结果",
  },
  "oauth.storageUnavailable": {
    ko: "저장소 사용 불가",
    en: "storage unavailable",
    ja: "storage unavailable",
    zh: "storage unavailable",
  },
  "oauth.executionReady": { ko: "실행 가능", en: "execution ready", ja: "execution ready", zh: "execution ready" },
  "oauth.reauthRequired": { ko: "재연결 필요", en: "reauth required", ja: "reauth required", zh: "reauth required" },
  "oauth.connectable": { ko: "연결 가능", en: "connectable", ja: "connectable", zh: "connectable" },
  "oauth.unavailable": { ko: "연결 불가", en: "unavailable", ja: "unavailable", zh: "unavailable" },
  "grid.installFailed": {
    ko: "Codex 앱 설치 실패: {error}",
    en: "Codex app install failed: {error}",
    ja: "Codex app install failed: {error}",
    zh: "Codex app install failed: {error}",
  },
  "grid.codexInstalled": { ko: "Codex 설치됨", en: "Codex installed", ja: "Codex installed", zh: "Codex installed" },
  "grid.installs": { ko: "설치", en: "installs", ja: "installs", zh: "installs" },
  "grid.installToCodexTitle": {
    ko: "repo seed skill을 Codex 앱 skill home에 설치",
    en: "Install repo seed skill into the Codex app skill home",
    ja: "Install repo seed skill into the Codex app skill home",
    zh: "Install repo seed skill into the Codex app skill home",
  },
  "grid.installing": { ko: "설치중", en: "Installing", ja: "Installing", zh: "Installing" },
  "grid.installed": { ko: "설치됨", en: "Installed", ja: "Installed", zh: "Installed" },
  "grid.installToCodex": {
    ko: "Codex 앱에 설치",
    en: "Install to Codex",
    ja: "Install to Codex",
    zh: "Install to Codex",
  },
  "grid.learnTitle": {
    ko: "선택한 CLI 대표에게 이 skill을 학습시킵니다",
    en: "Teach this skill to selected CLI leaders",
    ja: "Teach this skill to selected CLI leaders",
    zh: "Teach this skill to selected CLI leaders",
  },
  "grid.learn": { ko: "학습", en: "Learn", ja: "Learn", zh: "Learn" },
  "grid.copied": { ko: "복사됨", en: "Copied", ja: "Copied", zh: "Copied" },
  "grid.copy": { ko: "복사", en: "Copy", ja: "Copy", zh: "Copy" },
  "grid.detailsLoading": {
    ko: "상세 정보 로딩중...",
    en: "Loading details...",
    ja: "Loading details...",
    zh: "Loading details...",
  },
  "grid.detailsError": {
    ko: "상세 정보를 불러오지 못했습니다",
    en: "Could not load details",
    ja: "Could not load details",
    zh: "Could not load details",
  },
  "grid.whenToUse": { ko: "사용 시점", en: "When to Use", ja: "When to Use", zh: "When to Use" },
  "grid.weekly": { ko: "주간", en: "weekly", ja: "weekly", zh: "weekly" },
  "grid.firstSeen": { ko: "최초 등록", en: "First seen", ja: "First seen", zh: "First seen" },
  "grid.targetPlatforms": { ko: "대상 플랫폼", en: "Target Platforms", ja: "Target Platforms", zh: "Target Platforms" },
  "grid.noResults": {
    ko: "검색 결과가 없습니다",
    en: "No search results",
    ja: "No search results",
    zh: "No search results",
  },
  "grid.tryDifferentKeyword": {
    ko: "다른 키워드로 검색해보세요",
    en: "Try a different keyword",
    ja: "Try a different keyword",
    zh: "Try a different keyword",
  },
  "custom.title": {
    ko: "커스텀 Skill 추가",
    en: "Add Custom Skill",
    ja: "カスタム Skill 追加",
    zh: "添加自定义 Skill",
  },
  "custom.description": {
    ko: "skills.md 파일을 첨부하고 학습 대상 CLI 대표를 선택하세요.",
    en: "Attach a skills.md file and select CLI representatives.",
    ja: "skills.md ファイルを添付し、学習対象の CLI 代表を選択してください。",
    zh: "附加 skills.md 文件并选择要学习的 CLI 代表。",
  },
  "action.close": { ko: "닫기", en: "Close", ja: "閉じる", zh: "关闭" },
  "custom.nameLabel": { ko: "Skill 이름", en: "Skill Name", ja: "Skill 名", zh: "Skill 名称" },
  "custom.namePlaceholder": {
    ko: "예: my-custom-skill",
    en: "e.g. my-custom-skill",
    ja: "例: my-custom-skill",
    zh: "例如：my-custom-skill",
  },
  "custom.nameHelp": {
    ko: "영문, 숫자, 대시(-), 언더스코어(_)만 사용할 수 있습니다.",
    en: "Only alphanumeric, dash (-), and underscore (_) are allowed.",
    ja: "英数字、ダッシュ(-)、アンダースコア(_)のみ使用できます。",
    zh: "仅允许字母数字、短横线(-)和下划线(_)。",
  },
  "custom.fileLabel": { ko: "skills.md 파일", en: "skills.md File", ja: "skills.md ファイル", zh: "skills.md 文件" },
  "custom.chooseFile": { ko: "파일 선택", en: "Choose File", ja: "ファイル選択", zh: "选择文件" },
  "custom.providersLabel": {
    ko: "학습 대상 CLI 대표",
    en: "CLI Representatives to Train",
    ja: "学習対象 CLI 代表",
    zh: "要训练的 CLI 代表",
  },
  "custom.none": { ko: "없음", en: "None", ja: "なし", zh: "无" },
  "action.cancel": { ko: "취소", en: "Cancel", ja: "Cancel", zh: "Cancel" },
  "custom.submitting": { ko: "등록중...", en: "Submitting...", ja: "Submitting...", zh: "Submitting..." },
  "custom.startTraining": { ko: "학습 시작", en: "Start Training", ja: "Start Training", zh: "Start Training" },
  "custom.sectionTitle": { ko: "사용자 Skill", en: "Custom Skills", ja: "Custom Skills", zh: "Custom Skills" },
  "custom.noMatches": {
    ko: "검색 조건에 맞는 사용자 Skill이 없습니다",
    en: "No custom skills match this search",
    ja: "No custom skills match this search",
    zh: "No custom skills match this search",
  },
  "action.delete": { ko: "삭제", en: "Delete", ja: "Delete", zh: "Delete" },
  "custom.fileReadFailed": {
    ko: "파일 읽기 실패",
    en: "Failed to read file",
    ja: "Failed to read file",
    zh: "Failed to read file",
  },
  "custom.invalidName": {
    ko: "Skill 이름은 영문, 숫자, 대시, 언더스코어만 사용할 수 있습니다. 최대 80자입니다.",
    en: "Skill name must be alphanumeric, dash or underscore (max 80 chars).",
    ja: "Skill name must be alphanumeric, dash or underscore (max 80 chars).",
    zh: "Skill name must be alphanumeric, dash or underscore (max 80 chars).",
  },
  "learning.title": {
    ko: "스킬 학습 스쿼드",
    en: "Skill Learning Squad",
    ja: "Skill Learning Squad",
    zh: "Skill Learning Squad",
  },
  "learning.running": { ko: "학습중", en: "Running", ja: "Running", zh: "Running" },
  "learning.installCommand": { ko: "설치 명령", en: "Install command", ja: "Install command", zh: "Install command" },
  "learning.selectProviders": {
    ko: "CLI 대표를 선택하세요. 복수 선택 가능",
    en: "Select CLI representatives. Multi-select is supported.",
    ja: "Select CLI representatives. Multi-select is supported.",
    zh: "Select CLI representatives. Multi-select is supported.",
  },
  "learning.selectedCount": { ko: "명 선택됨", en: " selected", ja: " selected", zh: " selected" },
  "learning.noAssignedMember": {
    ko: "배정된 인원 없음",
    en: "No assigned member",
    ja: "No assigned member",
    zh: "No assigned member",
  },
  "learning.bonk": { ko: "정리!", en: "Bonk!", ja: "Bonk!", zh: "Bonk!" },
  "learning.unavailable": { ko: "사용 불가", en: "Unavailable", ja: "Unavailable", zh: "Unavailable" },
  "learning.learned": { ko: "학습됨", en: "Learned", ja: "Learned", zh: "Learned" },
  "learning.selected": { ko: "선택됨", en: "Selected", ja: "Selected", zh: "Selected" },
  "learning.idle": { ko: "대기", en: "Idle", ja: "Idle", zh: "Idle" },
  "learning.unlearning": { ko: "학습 취소중...", en: "Unlearning...", ja: "Unlearning...", zh: "Unlearning..." },
  "learning.unlearn": { ko: "학습 취소", en: "Unlearn", ja: "Unlearn", zh: "Unlearn" },
  "learning.jobStatus": { ko: "작업 상태", en: "Job status", ja: "Job status", zh: "Job status" },
  "learning.noLogs": { ko: "로그가 아직 없습니다", en: "No logs yet", ja: "No logs yet", zh: "No logs yet" },
  "learning.learning": { ko: "학습중...", en: "Learning...", ja: "Learning...", zh: "Learning..." },
  "learning.startLearning": {
    ko: "학습 시작",
    en: "Start Learning",
    ja: "Start Learning",
    zh: "Start Learning",
  },
  "classroom.training": {
    ko: '"{skill}" Skill 교육 진행중...',
    en: 'Training "{skill}" skill...',
    ja: 'Training "{skill}" skill...',
    zh: 'Training "{skill}" skill...',
  },
  "classroom.studying": {
    ko: "CLI 대표들이 학습 중입니다.",
    en: "CLI representatives are studying.",
    ja: "CLI representatives are studying.",
    zh: "CLI representatives are studying.",
  },
  "memory.title": { ko: "학습 메모리", en: "Learning Memory", ja: "Learning Memory", zh: "Learning Memory" },
  "memory.subtitle": {
    ko: "CLI별 Skill 이력",
    en: "Per-CLI skill history",
    ja: "Per-CLI skill history",
    zh: "Per-CLI skill history",
  },
  "audit.pass": { ko: "통과", en: "Pass", ja: "合格", zh: "通过" },
  "audit.warn": { ko: "경고", en: "Warn", ja: "警告", zh: "警告" },
  "audit.pending": { ko: "대기", en: "Pending", ja: "保留", zh: "待处理" },
  "audit.fail": { ko: "실패", en: "Fail", ja: "失敗", zh: "失败" },
  "role.team_leader": { ko: "팀장", en: "Team Lead", ja: "チームリード", zh: "团队负责人" },
  "role.senior": { ko: "시니어", en: "Senior", ja: "シニア", zh: "资深" },
  "role.junior": { ko: "주니어", en: "Junior", ja: "ジュニア", zh: "初级" },
  "role.intern": { ko: "인턴", en: "Intern", ja: "インターン", zh: "实习生" },
  "learnStatus.queued": { ko: "대기중", en: "Queued", ja: "待機中", zh: "排队中" },
  "learnStatus.running": { ko: "실행중", en: "Running", ja: "実行中", zh: "运行中" },
  "learnStatus.succeeded": { ko: "완료", en: "Succeeded", ja: "成功", zh: "成功" },
  "learnStatus.failed": { ko: "실패", en: "Failed", ja: "失敗", zh: "失败" },
} as const satisfies Record<string, Record<Locale, string>>;

export type SkillLibraryTextKey = keyof typeof SKILL_LIBRARY_TEXT;

export function skillText(t: SkillLibraryT, key: SkillLibraryTextKey): string {
  return t(SKILL_LIBRARY_TEXT[key]);
}

export function skillTextVars(
  t: SkillLibraryT,
  key: SkillLibraryTextKey,
  vars: Record<string, string | number>,
): string {
  return skillText(t, key).replace(/\{(\w+)\}/g, (match, name: string) => {
    const value = vars[name];
    return value === undefined ? match : String(value);
  });
}
