[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string] $PromptFile,

  [Parameter(Mandatory = $true)]
  [string] $OutputPath,

  [string] $PrimaryModel = "gemini-3.1-pro-preview",
  [string] $FallbackModel = "gemini-2.5-pro",
  [int] $TimeoutSeconds = 900
)

$ErrorActionPreference = "Stop"

function Read-Utf8File {
  param([Parameter(Mandatory = $true)][string] $Path)
  $resolved = (Resolve-Path -LiteralPath $Path).Path
  return [System.IO.File]::ReadAllText($resolved, [System.Text.UTF8Encoding]::new($false))
}

function Write-Utf8NoBom {
  param(
    [Parameter(Mandatory = $true)][string] $Path,
    [Parameter(Mandatory = $true)][string] $Content
  )
  $fullPath = [System.IO.Path]::GetFullPath($Path)
  $dir = [System.IO.Path]::GetDirectoryName($fullPath)
  if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  [System.IO.File]::WriteAllText($fullPath, $Content, [System.Text.UTF8Encoding]::new($false))
}

function Invoke-GeminiModel {
  param(
    [Parameter(Mandatory = $true)][string] $Model,
    [Parameter(Mandatory = $true)][string] $Prompt,
    [Parameter(Mandatory = $true)][int] $Timeout
  )

  $geminiCommand = Get-Command gemini -ErrorAction Stop
  $baseDir = Split-Path -Parent $geminiCommand.Source
  $geminiJs = Join-Path $baseDir "node_modules\@google\gemini-cli\bundle\gemini.js"
  if (-not (Test-Path -LiteralPath $geminiJs -PathType Leaf)) {
    throw "Gemini CLI bundle was not found at $geminiJs."
  }
  $nodeCommand = Get-Command node -ErrorAction Stop

  $psi = New-Object System.Diagnostics.ProcessStartInfo
  $psi.FileName = $nodeCommand.Source
  $psi.WorkingDirectory = (Get-Location).Path
  $psi.UseShellExecute = $false
  $psi.RedirectStandardInput = $true
  $psi.RedirectStandardOutput = $true
  $psi.RedirectStandardError = $true
  $psi.StandardOutputEncoding = [System.Text.UTF8Encoding]::new($false)
  $psi.StandardErrorEncoding = [System.Text.UTF8Encoding]::new($false)
  $psi.EnvironmentVariables["GEMINI_CLI_TRUST_WORKSPACE"] = "true"
  $psi.Arguments = @(
    "--no-warnings=DEP0040",
    "`"$geminiJs`"",
    "-m",
    "`"$Model`"",
    "--approval-mode",
    "plan",
    "-p",
    "`"Return only the requested markdown report. Use the full prompt from stdin.`""
  ) -join " "

  $process = [System.Diagnostics.Process]::Start($psi)
  $stdoutTask = $process.StandardOutput.ReadToEndAsync()
  $stderrTask = $process.StandardError.ReadToEndAsync()
  $process.StandardInput.Write($Prompt)
  $process.StandardInput.Close()

  if (-not $process.WaitForExit($Timeout * 1000)) {
    try {
      $process.Kill()
    } catch {
      # ignore cleanup race
    }
    return [pscustomobject]@{
      Model = $Model
      ExitCode = 124
      TimedOut = $true
      IsCapacity429 = $false
      Stdout = ""
      Stderr = "timed_out_after_${Timeout}s"
    }
  }

  $stdout = $stdoutTask.Result
  $stderr = $stderrTask.Result
  $exitCode = $process.ExitCode
  $isCapacity429 = ($stdout -match "429|MODEL_CAPACITY_EXHAUSTED|RESOURCE_EXHAUSTED|No capacity") -or
    ($stderr -match "429|MODEL_CAPACITY_EXHAUSTED|RESOURCE_EXHAUSTED|No capacity")

  return [pscustomobject]@{
    Model = $Model
    ExitCode = $exitCode
    TimedOut = $false
    IsCapacity429 = $isCapacity429
    Stdout = $stdout
    Stderr = $stderr
  }
}

$promptText = Read-Utf8File -Path $PromptFile
$primary = Invoke-GeminiModel -Model $PrimaryModel -Prompt $promptText -Timeout $TimeoutSeconds
$effective = $primary
$fallbackUsed = $false

if ($primary.ExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($primary.Stdout) -or $primary.IsCapacity429) {
  $effective = Invoke-GeminiModel -Model $FallbackModel -Prompt $promptText -Timeout $TimeoutSeconds
  $fallbackUsed = $true
}

if ([string]::IsNullOrWhiteSpace($effective.Stdout)) {
  throw "Gemini analysis failed. primary=$($primary.Model) exit=$($primary.ExitCode) capacity429=$($primary.IsCapacity429); fallback=$($effective.Model) exit=$($effective.ExitCode) capacity429=$($effective.IsCapacity429)"
}

$header = @"
<!--
Generated by scripts/run-gemini-pro-analysis.ps1.
PrimaryModel: $($primary.Model)
PrimaryExitCode: $($primary.ExitCode)
PrimaryCapacity429: $($primary.IsCapacity429)
FallbackModel: $FallbackModel
FallbackUsed: $fallbackUsed
EffectiveModel: $($effective.Model)
EffectiveExitCode: $($effective.ExitCode)
TrustedWorkspaceEnv: GEMINI_CLI_TRUST_WORKSPACE=true
-->

"@

Write-Utf8NoBom -Path $OutputPath -Content ($header + $effective.Stdout)
Write-Host "primary_model=$($primary.Model)"
Write-Host "primary_exit=$($primary.ExitCode)"
Write-Host "primary_capacity429=$($primary.IsCapacity429)"
Write-Host "fallback_used=$fallbackUsed"
Write-Host "effective_model=$($effective.Model)"
Write-Host "output=$([System.IO.Path]::GetFullPath($OutputPath))"
