import type { TFunction } from "./types";

export function getSettingsCommonCopy(t: TFunction) {
  return {
    refresh: t({ ko: "?덈줈怨좎묠", en: "Refresh" }),
    add: t({ ko: "異붽?", en: "Add" }),
    edit: t({ ko: "?섏젙", en: "Edit" }),
    update: t({ ko: "?낅뜲?댄듃", en: "Update" }),
    delete: t({ ko: "??젣", en: "Delete" }),
    cancel: t({ ko: "痍⑥냼", en: "Cancel" }),
    close: t({ ko: "?リ린", en: "Close" }),
    confirm: t({ ko: "?뺤씤", en: "Confirm" }),
    loading: t({ ko: "遺덈윭?ㅻ뒗 以?..", en: "Loading..." }),
    saving: t({ ko: "???以?..", en: "Saving..." }),
    enabled: t({ ko: "?쒖꽦", en: "Enabled" }),
    disabled: t({ ko: "비활성", en: "Disabled" }),
    enable: t({ ko: "?쒖꽦??", en: "Enable" }),
    disable: t({ ko: "鍮꾪솢?깊솕", en: "Disable" }),
    test: t({ ko: "?뚯뒪??", en: "Test" }),
    receiver: t({ ko: "?섏떊湲?", en: "Receiver" }),
    runtime: t({ ko: "?고???", en: "Runtime" }),
    models: t({ ko: "紐⑤뜽", en: "Models" }),
    searchModels: t({ ko: "紐⑤뜽 寃??", en: "Search models" }),
    noResults: t({ ko: "寃??寃곌낵 ?놁쓬", en: "No results" }),
    assign: t({ ko: "?좊떦", en: "Assign" }),
    applied: t({ ko: "?곸슜??", en: "Applied" }),
    unassigned: t({ ko: "誘명븷??", en: "Unassigned" }),
  };
}
export function getApiSettingsCopy(t: TFunction) {
  return {
    title: t({ ko: "API ?쒓났??", en: "API Providers" }),
    intro: t({
      ko: "濡쒖뺄, ?꾨줎?곗뼱, ?명솚 API瑜??깅줉?섍퀬 ?먯씠?꾪듃 ?ㅽ뻾怨??곌껐?⑸땲??",
      en: "Register local, frontier, and compatible APIs, then connect them to agent execution.",
    }),
    editProvider: t({ ko: "?쒓났???섏젙", en: "Edit Provider" }),
    addProvider: t({ ko: "???쒓났??異붽?", en: "Add New Provider" }),
    officialPresets: t({ ko: "怨듭떇 ?꾨━??", en: "Official Presets" }),
    officialPresetsHelp: t({
      ko: "OpenCode Go? Bailian Coding Plan 怨듭떇 ?꾨━?뗭엯?덈떎.",
      en: "Official presets for OpenCode Go and Bailian Coding Plan.",
    }),
    presetsLoading: t({ ko: "?꾨━??遺덈윭?ㅻ뒗 以?..", en: "Loading presets..." }),
    presetsFailed: t({ ko: "怨듭떇 ?꾨━?뗭쓣 遺덈윭?ㅼ? 紐삵뻽?듬땲??", en: "Official presets could not be loaded." }),
    openDocs: t({ ko: "臾몄꽌 ?닿린", en: "Open docs" }),
    genericType: t({ ko: "?쇰컲 ???", en: "Generic Type" }),
    genericTypeHelpLocked: t({
      ko: "?쇰컲 ??낆쓣 ?좏깮?섎㈃ ?꾨━??紐⑤뱶瑜??댁젣?섍퀬 ?섎룞 ?몄쭛???ъ슜?????덉뒿?덈떎.",
      en: "Choose a generic type to leave preset mode and unlock manual editing.",
    }),
    genericTypeHelpManual: t({
      ko: "?꾨줈?좎퐳怨?Base URL??吏곸젒 愿由ы븯?ㅻ㈃ ?쇰컲 ??낆쓣 ?ъ슜?섏꽭??",
      en: "Use a generic type when you want to manage protocol and Base URL yourself.",
    }),
    name: t({ ko: "?대쫫", en: "Name" }),
    namePlaceholder: t({ ko: "?? My OpenAI", en: "e.g. My OpenAI" }),
    baseUrlManagedByPreset: t({
      ko: "?좏깮???꾨━?뗭씠 ?꾨줈?좎퐳怨?Base URL??愿由ы빀?덈떎.",
      en: "The selected preset manages the protocol and Base URL.",
    }),
    usuallyNotNeededForLocal: t({ ko: "濡쒖뺄 ?섍꼍?먯꽌??蹂댄넻 ?꾩슂?섏? ?딆쓬", en: "usually not needed for local" }),
    changeApiKeyPlaceholder: t({ ko: "蹂寃쏀븯?ㅻ㈃ ?낅젰 (鍮꾩슦硫??좎?)", en: "Enter to change (blank=keep)" }),
    noProviders: t({
      ko: "?깅줉??API ?쒓났?먭? ?놁뒿?덈떎. ?곷떒??異붽? 踰꾪듉?쇰줈 ?쒖옉?섏꽭??",
      en: "No API providers registered. Click Add above to get started.",
    }),
    testConnection: t({ ko: "?곌껐 ?뚯뒪??", en: "Test Connection" }),
    assignToAgent: t({ ko: "?먯씠?꾪듃???좊떦", en: "Assign to agent" }),
  };
}

export function getGatewaySettingsCopy(t: TFunction) {
  return {
    title: t({ ko: "梨꾨꼸 硫붿떆吏 ?ㅼ젙", en: "Channel Messaging" }),
    intro: t({
      ko: "????뿉??硫붿떊? 梨꾨꼸??吏곸젒 ?ㅼ젙?????덉뒿?덈떎. 梨꾪똿 異붽?濡?硫붿떊?, ?좏겙, ???ID, ?곌껐 ?먯씠?꾪듃瑜??깅줉?섏꽭??",
      en: "Configure messenger channels directly in this tab. Use Add Chat to register messenger, token, target ID, and conversation agent.",
    }),
    chatSessions: t({ ko: "梨꾪똿 ?몄뀡", en: "Chat Sessions" }),
    addChat: t({ ko: "梨꾪똿 異붽?", en: "Add Chat" }),
    noChats: t({
      ko: "?깅줉??梨꾪똿???놁뒿?덈떎. 梨꾪똿 異붽?濡?硫붿떊?, ?좏겙, 梨꾨꼸???깅줉?섏꽭??",
      en: "No chats yet. Use Add Chat to register messenger, token, and channel.",
    }),
    noToken: t({ ko: "?좏겙 ?놁쓬", en: "No token" }),
    native: t({ ko: "吏곸젒 ?곌껐", en: "Native" }),
    compat: t({ ko: "?명솚 ?ㅼ젙", en: "Compat" }),
    assignedAgent: t({ ko: "?곌껐 ?먯씠?꾪듃", en: "Agent" }),
    noAssignedAgent: t({ ko: "?곌껐???먯씠?꾪듃 ?놁쓬", en: "No agent assigned" }),
    directiveRoutingHelp: t({
      ko: "$濡??쒖옉?섎㈃ ?뚯궗 吏?쒓? ?섍퀬, ?쇰컲 硫붿떆吏???좏깮???먯씠?꾪듃?먭쾶 1:1濡??꾨떖?⑸땲??",
      en: "Messages starting with $ become company directives; normal messages go 1:1 to the selected agent.",
    }),
    testSend: t({ ko: "?뚯뒪???꾩넚", en: "Test Send" }),
    telegramReceiver: t({ ko: "?붾젅洹몃옩 ?섏떊湲?", en: "Telegram Receiver" }),
    discordReceiver: t({ ko: "?붿뒪肄붾뱶 ?섏떊湲?", en: "Discord Receiver" }),
    allowedChats: t({ ko: "?덉슜??梨꾪똿 ??", en: "Allowed chats" }),
    polledChannels: t({ ko: "?대쭅 梨꾨꼸 ??", en: "Polled channels" }),
    targetSession: t({ ko: "????몄뀡", en: "Target Session" }),
    noSavedSession: t({
      ko: "??λ맂 ?몄뀡???놁뒿?덈떎. 癒쇱? 梨꾪똿??異붽??섏꽭??",
      en: "No saved session. Add a chat first.",
    }),
    testMessagePlaceholder: t({ ko: "?뚯뒪??硫붿떆吏瑜??낅젰?섏꽭??..", en: "Type a test message..." }),
    transportNotReady: t({
      ko: "??梨꾨꼸? ?ㅼ젙怨?留ㅽ븨? 媛?ν븯吏留?吏곸젒 ?꾩넚 ?고??꾩? ?꾩쭅 以鍮꾨릺吏 ?딆븯?듬땲??",
      en: "This channel can be configured and mapped, but direct transport runtime is not ready yet.",
    }),
    send: t({ ko: "硫붿떆吏 ?꾩넚", en: "Send" }),
    sending: t({ ko: "?꾩넚 以?..", en: "Sending..." }),
    messageSent: t({ ko: "硫붿떆吏 ?꾩넚 ?꾨즺", en: "Message sent" }),
    channelSettingsSaved: t({ ko: "梨꾨꼸 ?ㅼ젙 ????꾨즺", en: "Channel settings saved" }),
    chatDeleted: t({ ko: "梨꾪똿 ??젣 ?꾨즺", en: "Chat deleted" }),
    chatSaved: t({ ko: "梨꾪똿 ????꾨즺", en: "Chat saved" }),
    tokenRequired: t({ ko: "?좏겙???낅젰??二쇱꽭??", en: "Please enter a token." }),
    chatNameRequired: t({ ko: "梨꾪똿 ?대쫫???낅젰??二쇱꽭??", en: "Please enter a chat name." }),
    targetIdRequired: t({ ko: "梨꾨꼸 ?먮뒗 ???ID瑜??낅젰??二쇱꽭??", en: "Please enter a channel or target ID." }),
    saveChatFailed: t({
      ko: "梨꾪똿 ??μ뿉 ?ㅽ뙣?덉뒿?덈떎. ?ㅼ떆 ?쒕룄??二쇱꽭??",
      en: "Failed to save chat. Please try again.",
    }),
    runtimeSessions: t({ ko: "?고????몄뀡", en: "Runtime Sessions" }),
    singleGroupMode: t({ ko: "단일 그룹 모드", en: "Single Group Mode" }),
    editGlobalChat: t({ ko: "전역 그룹 설정", en: "Edit Global Group" }),
    globalSessionName: t({ ko: "전역 텔레그램 그룹", en: "Global Telegram Group" }),
    singleGroupNotice: t({
      ko: "부서 구분은 채널 분리가 아니라 메시지 헤더 태그로 처리됩니다.",
      en: "Department routing uses message header tags in one shared group.",
    }),
  };
}

export function getOauthSettingsCopy(t: TFunction) {
  return {
    title: t({ ko: "OAuth ?몄쬆 ?꾪솴", en: "OAuth Status" }),
    connectFailed: t({ ko: "OAuth ?곌껐 ?ㅽ뙣", en: "OAuth connection failed" }),
    connected: t({ ko: "?곌껐 ?꾨즺", en: "connected" }),
    storageReady: t({
      ko: "OAuth ??μ냼 ?쒖꽦 (?뷀샇?????ㅼ젙??",
      en: "OAuth storage is active (encryption key configured)",
    }),
    storageMissing: t({
      ko: "OAUTH_ENCRYPTION_SECRET ?섍꼍蹂?섍? ?ㅼ젙?섏? ?딆븯?듬땲??",
      en: "OAUTH_ENCRYPTION_SECRET is not set.",
    }),
    connectionStatus: t({ ko: "?곌껐 ?곹깭", en: "Connection Status" }),
    cliDetected: t({ ko: "CLI 媛먯?", en: "CLI detected" }),
    detectedNotRunnable: t({ ko: "媛먯???(?ㅽ뻾 遺덇?)", en: "Detected (not runnable)" }),
    autoRefreshed: t({ ko: "?먮룞 媛깆떊??", en: "Auto-refreshed" }),
    refreshFailed: t({ ko: "媛깆떊 ?ㅽ뙣", en: "Refresh failed" }),
    expiredReauth: t({ ko: "留뚮즺 - ?ъ씤利??꾩슂", en: "Expired - re-auth needed" }),
    expired: t({ ko: "留뚮즺??", en: "Expired" }),
    reconnect: t({ ko: "?ㅼ떆 ?곌껐", en: "Reconnect" }),
    disconnecting: t({ ko: "?곌껐 ?댁젣 以?..", en: "Disconnecting..." }),
    disconnect: t({ ko: "?곌껐 ?댁젣", en: "Disconnect" }),
    cliCredentialWarning: t({
      ko: "CLI?먯꽌 媛먯????먭꺽 利앸챸? Claw-Empire ?ㅽ뻾??吏곸젒 ?ъ슜?섏? ?딆뒿?덈떎. Web OAuth濡??ㅼ떆 ?곌껐?섏꽭??",
      en: "CLI-detected credentials are not used directly for Claw-Empire execution. Reconnect with Web OAuth.",
    }),
    scope: t({ ko: "沅뚰븳 踰붿쐞", en: "Scope" }),
    expires: t({ ko: "留뚮즺 ?쒓컖", en: "Expires" }),
    created: t({ ko: "?깅줉 ?쒓컖", en: "Created" }),
    providerDefaultModel: t({ ko: "Provider 湲곕낯 紐⑤뜽", en: "Provider Default Model" }),
    selectPlaceholder: t({ ko: "?좏깮?섏꽭??..", en: "Select..." }),
    noModelsAvailable: t({ ko: "?ъ슜 媛?ν븳 紐⑤뜽???놁뒿?덈떎", en: "No models available" }),
    copilotSubscriptionHint: t({
      ko: "GitHub Copilot 援щ룆???덉뼱??紐⑤뜽 ?ㅽ뻾??媛?ν빀?덈떎. ??μ냼 媛?몄삤湲곕쭔 ?꾩슂?섎㈃ 臾댁떆?대룄 ?⑸땲??",
      en: "Model execution requires a GitHub Copilot subscription. Ignore this if you only need repository import.",
    }),
    executionAccountPool: t({ ko: "?ㅽ뻾 怨꾩젙 ?", en: "Execution Account Pool" }),
    accountPoolHint: t({
      ko: "?щ윭 ?쒖꽦 怨꾩젙??吏?먰빀?덈떎. priority ?レ옄媛 ??쓣?섎줉 癒쇱? ?쒕룄?⑸땲??",
      en: "Multiple active accounts are supported. Lower priority values run first.",
    }),
    active: t({ ko: "?쒖꽦", en: "Active" }),
    standby: t({ ko: "?湲?", en: "Standby" }),
    runnable: t({ ko: "?ㅽ뻾 媛??", en: "Runnable" }),
    notRunnable: t({ ko: "?ㅽ뻾 遺덇?", en: "Not runnable" }),
    label: t({ ko: "?쇰꺼", en: "Label" }),
    accountAlias: t({ ko: "怨꾩젙 蹂꾩묶", en: "Account alias" }),
    modelOverride: t({ ko: "紐⑤뜽 ?ㅻ쾭?쇱씠??", en: "Model Override" }),
    useProviderDefault: t({ ko: "Provider 湲곕낯媛??ъ슜", en: "Use provider default" }),
    priority: t({ ko: "?곗꽑?쒖쐞", en: "Priority" }),
    poolOff: t({ ko: "? 鍮꾪솢??", en: "Pool Off" }),
    poolOn: t({ ko: "? ?쒖꽦", en: "Pool On" }),
    save: t({ ko: "???", en: "Save" }),
    executionAccounts: t({ ko: "?ㅽ뻾 怨꾩젙 ?곌껐", en: "Execution Accounts" }),
    encryptionKeyRequired: t({ ko: "?뷀샇?????꾩슂", en: "Encryption key required" }),
    executionReady: t({ ko: "?ㅽ뻾 以鍮??꾨즺", en: "Execution Ready" }),
    reauthRequired: t({ ko: "?ъ뿰寃??꾩슂", en: "Re-auth Required" }),
    connectable: t({ ko: "?곌껐 媛??", en: "Connectable" }),
    waitingDeviceCode: t({ ko: "湲곌린 肄붾뱶瑜??낅젰?섎뒗 以묒엯?덈떎...", en: "Waiting for device-code confirmation..." }),
    connect: t({ ko: "?곌껐", en: "Connect" }),
    addAccount: t({ ko: "怨꾩젙 異붽?", en: "Add Account" }),
    githubAccountConnected: t({ ko: "GitHub ?ㅽ뻾 怨꾩젙 ?곌껐 ?꾨즺", en: "GitHub execution account connected" }),
    githubAccountConnectedHelp: t({
      ko: "Copilot 援щ룆???덉쑝硫?AI 紐⑤뜽 ?ㅽ뻾???ъ슜?섍퀬, 援щ룆???놁뼱??GitHub 媛?몄삤湲곗? ??μ냼 ?곌껐? 怨꾩냽 ?ъ슜?????덉뒿?덈떎.",
      en: "If you have Copilot, it is used for AI execution. Without it, GitHub import and repository linking still work.",
    }),
  };
}
